# -*- coding: utf-8 -*-
"""thecustomerchurn1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/chibichip/thecustomerchurn1.808a2ee4-1de4-425b-8cf1-730e8d9a5195.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260226/auto/storage/goog4_request%26X-Goog-Date%3D20260226T111055Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D846b5830a980b2b940049ed87efe777fd0199d5289e9ed80dc58dbc47faf0c34c926791755bebeb263129211dc4810a3d563e3fa6399d9e6b026d3d3b96e7af8f03209d38b74a773dda8df950cf2edd1f773746e51b003d5ebd7e3a15ebb37937dbf67afd90351bd671b653b6e5e2a71a6d7e19629db7a4e1e109725024706dfd3d78611ba3dd36eef503e48f2f7464e98e95b69e4a3293981570fd1b126bd2637870b874cd8eb02f70508620ac64e0971ac4fedce2850e830546c369af04e3448ec5d98c98f3a3257beaab90890884314c801e28aa732cb5d84a22e0b27d3b822d93386aad50451f617e6c05b33b189e9c656687354d9da6f84872ba12fa55b
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
blastchar_telco_customer_churn_path = kagglehub.dataset_download('blastchar/telco-customer-churn')

print('Data source import complete.')

!pip install -U imbalanced-learn

import pandas as pd

# Load data
df = pd.read_csv('/kaggle/input/datasets/blastchar/telco-customer-churn/WA_Fn-UseC_-Telco-Customer-Churn.csv')

# 1. Drop customerID (it's useless for prediction)
df.drop('customerID', axis=1, inplace=True)

# 2. Fix TotalCharges: convert empty spaces to NaN and then to 0
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df['TotalCharges'].fillna(0, inplace=True)

# 3. Convert Churn (Target) to numbers: Yes = 1, No = 0
df['Churn'] = df['Churn'].map({'Yes': 1, 'No': 0})

print("✅ Data Cleaned!")
print(df.dtypes[['TotalCharges', 'Churn']])

# Create "Dummy" variables for all categorical text columns
df_final = pd.get_dummies(df, drop_first=True)

# Look at the new shape
print(f"Original columns: {len(df.columns)}")
print(f"New columns after encoding: {len(df_final.columns)}")
print(df_final.head())

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

# 1. Split into X (everything but Churn) and y (only Churn)
X = df_final.drop('Churn', axis=1)
y = df_final['Churn']

# 2. Split into Train (80%) and Test (20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. Initialize and Train the Model
# We use RandomForest because it's great for tabular data and handles "messy" features well
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# 4. Check the Results
predictions = model.predict(X_test)
print(classification_report(y_test, predictions))

# Train a "Balanced" model to improve Recall for churners
balanced_model = RandomForestClassifier(
    n_estimators=100,
    class_weight='balanced', # This is the magic line
    random_state=42
)

balanced_model.fit(X_train, y_train)

# Check the new results
balanced_preds = balanced_model.predict(X_test)
print("📊 BALANCED MODEL REPORT:")
print(classification_report(y_test, balanced_preds))

from imblearn.over_sampling import SMOTE
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

# 1. Initialize SMOTE
# sampling_strategy='minority' tells it to balance the smaller class (Churners)
sm = SMOTE(random_state=42)

# 2. Resample the training data
# This creates new synthetic examples for y=1
X_res, y_res = sm.fit_resample(X_train, y_train)

# 3. Train the model on the NEW balanced data
smote_model = RandomForestClassifier(n_estimators=100, random_state=42)
smote_model.fit(X_res, y_res)

# 4. Final Evaluation
smote_preds = smote_model.predict(X_test)
print("📊 SMOTE MODEL REPORT:")
print(classification_report(y_test, smote_preds))

import joblib

# 1. Save the model weights
joblib.dump(smote_model, 'churn_model.pkl')

# 2. Save the column names
# (This ensures your FastAPI app uses the exact same input order)
joblib.dump(list(X.columns), 'model_columns.pkl')

print("✅ Model and Columns exported successfully!")